---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: upgrade all packages
    yum: name=epel-release state=latest update_cache=yes
  - name: upgrade all packages
    yum: name=* state=latest update_cache=yes
  - name: install all the internets
    yum: pkg=puppet,boost-devel,openssl-devel,yaml-cpp-devel,libblkid-devel,libcurl-devel,gcc-c++,make,wget,tar,git,ruby-devel,bzip2-devel,python-devel state=latest
  - name: get icu
    get_url: url=http://download.icu-project.org/files/icu4c/51.2/icu4c-51_2-src.tgz dest=/root/icu.tgz
  - name: untar icu
    command: tar xzvf /root/icu.tgz
    args:
      chdir: /root
  - name: install icu
    shell: ./configure && make && make install 
    args:
      chdir: /root/icu/source
  - name: get boost
    git: repo=https://github.com/boostorg/boost  dest=/root/boost
  - name: run bootstrap boost
    shell: ./bootstrap.sh  --with-libraries=all 
    args:
      chdir: /root/boost/
  - name: run b2 boos
    shell: ./b2
    args:
      chdir: /root/boost/
  - name: stall boost
    shell: ./b2 install --prefix=/usr
    args:
      chdir: /root/boost/
  - name: get cmake
    get_url: url=http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz dest=/root/cmake-3.2.3-Linux-x86_64.tar.gz
  - name: untar cmake
    command: tar xzvf /root/cmake-3.2.3-Linux-x86_64.tar.gz --strip 1 -C /usr/local
  - name: clone
    git: repo=https://github.com/puppetlabs/facter.git dest=/root/facter
  - name: Creates directory
    file: path=/root/facter/release state=directory
  - name: download foo.conf
    command: cmake ..
    args:
      chdir: /root/facter/release
  - name: Make facter
    shell: make
    args:
      chdir: /root/facter/release
  - name: Make facter install
    command: make install
    args:
      chdir: /root/facter/release
#  - name: write the apache config file
#    template: src=/srv/httpd.j2 dest=/etc/httpd.conf
#    notify:
#    - restart apache
#  - name: ensure apache is running (and enable it at boot)
#    service: name=httpd state=started enabled=yes
#  handlers:
#    - name: restart apache
#      service: name=httpd state=restarted
