# vim:ft=ansible:
---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: install all the internets
    copy: src=./files/sshd_config dest=/etc/ssh/sshd_config
  - name: upgrade all packages
    yum: name=epel-release state=latest update_cache=yes
  - name: upgrade all packages
    yum: name=* state=latest update_cache=yes
  - name: install all the internets
    yum: pkg=puppet,tcpdump,system-config-firewall-tui,boost-devel,openssl-devel,yaml-cpp-devel,libblkid-devel,libcurl-devel,gcc-c++,make,wget,tar,git,ruby-devel,bzip2-devel,python-devel,hiera,facter,net-tools,qemu-kvm,libvirt,virt-install,bridge-utils,bind-utils state=latest
  #- name: install all the internets
  #  shell: ip link set dev br0 address D4:3D:7E:ED:0A:56
  #- name: Restart sshd
  #  service: name=ssh state=restarted
  - name: add ssh key
    authorized_key: user=root key="{{ lookup('file', '/home/u/.ssh/id_rsa.pub') }}"  manage_dir=yes
  - name: upgrade all packages
    copy: src=./files/route-br0 dest=/etc/sysconfig/network-scripts/route-eth0  force=absent
  - name: upgrade all packages
    copy: src=./files/route-br0 dest=/etc/sysconfig/network-scripts/route-br0  force=yes
  - name: upgrade all packages
    copy: src=./files/ifcfg-eth0 dest=/etc/sysconfig/network-scripts/ifcfg-eth0  force=yes
  #- name: upgrade all packages
  #  copy: src=./files/ifcfg-eth1 dest=/etc/sysconfig/network-scripts/ifcfg-eth1  force=yes
  - name: upgrade all packages
    copy: src=./files/ifcfg-br0 dest=/etc/sysconfig/network-scripts/ifcfg-br0  force=yes
  - name: upgrade all packages
    copy: src=./files/tables dest=/root/tables force=yes
  - name: upgrade all packages
    shell: iptables-restore /root/tables
