---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
  - name: upgrade all packages
    yum: name=epel-release state=latest update_cache=yes
  - name: upgrade all packages
    yum: name=* state=latest update_cache=yes
  - name: install all the internets
    yum: pkg=puppet,boost-devel,openssl-devel,yaml-cpp-devel,libblkid-devel,libcurl-devel,gcc-c++,make,wget,tar,git,ruby-devel,bzip2-devel,python-devel,facter state=latest

